name: Update Vault content

on:
  schedule:
    - cron: "0 11 * * MON"
  workflow_dispatch:

jobs:
  update_vault_content:
    runs-on: ubuntu-latest
    steps:
      - name: Clone sousterre/roam
        uses: actions/checkout@v4.2.2
        with:
          repository: "sousterre/roam"
          ref: main
          ssh-key: ${{ secrets.ROAM_PULLER }}
          path: content
      - name: Check Content
        run: |
          ls -alR content
